main_app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from main_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin-fabrim/principal/',
         views.PrincipalTemplateView.as_view(), name='principal'),

    path('admin-fabrim/medicamentos/',
         views.MedicamentosView.as_view(), name='medicamentos'),
    path('admin-fabrim/medicamentos/delete/<int:pk>/',
         views.MedicamentoDeleteView.as_view(), name='delete_medicamento'),



    path('admin-fabrim/tipos-medicamentos/',
         views.TiposMedicamentosView.as_view(), name='tipos-medicamentos'),
    path('admin-fabrim/tarjetas-estiba/',
         views.TarjetasEstibaView.as_view(), name='tarjetas-estiba'),
    path('admin-fabrim/usuarios/',
         views.UsuariosView.as_view(), name='usuarios'),
    path('admin-fabrim/compras/',
         views.ComprasView.as_view(), name='compras'),
    path('admin-fabrim/pedidos/',
         views.PedidosView.as_view(), name='pedidos'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

p5_isw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_app.urls")),
]

main_app/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
# from django.utils.translation import gettext_lazy as _


# Create your models here.
class UserManager(BaseUserManager):
    """Manager para usuarios"""

    def create_user(self, email, name, apellidos,  ci, tfno, password=None, **extra_fields):
        """Crea un nuevo Usuario"""
        if not email:
            raise ValueError("El usuario debe tener un email")

        email = self.normalize_email(email)
        user = self.model(email=email, name=name,
                          apellidos=apellidos, ci=ci, tfno=tfno, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, apellidos,  ci, tfno, password=None, **extra_fields):
        user = self.create_user(email, name, apellidos, ci, tfno,
                                password, **extra_fields)

        user.is_superuser = True
        user.is_staff = True

        user.set_password(password)
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Modelo BD para Users"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    apellidos = models.CharField(max_length=255)
    ci = models.CharField(max_length=11, unique=True, null=False, blank=False)
    tfno = models.CharField(max_length=50)
    apto = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'apellidos', 'ci', 'tfno']

    def get_full_name(self):
        return "%s %s" % (self.name, self.apellidos)

    def get_short_name(self):
        return self.name

    def __str__(self):
        """Return String"""
        return self.email


class TipoMedicamento(models.Model):
    nombre = models.CharField(
        max_length=255, unique=True, null=False, blank=False)

    def __str__(self):
        """Return String"""
        return self.nombre


class TarjetaEstiba(models.Model):
    no_serie = models.CharField(
        max_length=255, unique=True, null=False, blank=False)
    precio = models.IntegerField(blank=False, null=False)
    cant_medi = models.IntegerField(blank=False, null=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)

    class Meta:
        ordering = ['no_serie', 'fecha_creacion']

    def __str__(self):
        return "%s %s %s %s" % (self.no_serie, self.precio, self.cant_medi, self.fecha_creacion)


class Medicamento(models.Model):
    nombre = models.CharField(max_length=255, blank=False, null=False)
    no_lote = models.CharField(
        max_length=255, unique=True, null=False, blank=False)
    fecha_cad = models.DateField(blank=False, null=False, default=(
        timezone.now() + timedelta(days=1825)))
    tarjeta_estiba_id = models.OneToOneField(
        TarjetaEstiba, on_delete=models.CASCADE, primary_key=True)
    tipo_medicamento_id = models.ForeignKey(
        TipoMedicamento, on_delete=models.CASCADE)

    class Meta:
        ordering = ['fecha_cad', 'no_lote', 'nombre']

    def __str__(self):
        return "%s - %s - %s" % (self.nombre, self.no_lote, self.fecha_cad)


class Pedido(models.Model):
    cantidad_medicamento = models.IntegerField(blank=False, null=False)
    fecha = models.DateField(blank=False, null=False, auto_now=True)
    medicamentos = models.ManyToManyField(Medicamento)

    class Meta:
        ordering = ['fecha']

    def __str__(self):
        return "%s %s" % (self.cantidad_medicamento, self.fecha)


class Compra(models.Model):
    fecha = models.DateField(blank=False, null=False, auto_now=True)
    tarjeta_bancaria = models.CharField(
        max_length=255, null=False, blank=False)
    total_pagado = models.IntegerField(blank=False, null=False)
    medicamentos = models.ManyToManyField(Medicamento)
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)

main_app/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
import main_app.models as _


class LoginForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control form-control-lg'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg'}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)


class RegisterForm(forms.ModelForm):
    class Meta:
        model = _.User
        fields = ('__all__')
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-lg '}),
            'apellidos': forms.TextInput(
                attrs={'class': 'form-control form-control-lg '}),
            'ci': forms.TextInput(
                attrs={'class': 'form-control form-control-lg '}),
            'tfno': forms.TextInput(
                attrs={'class': 'form-control form-control-lg '}),
            'apto': forms.TextInput(
                attrs={'class': 'form-control form-control-lg '}),
            'email': forms.EmailInput(
                attrs={'class': 'form-control form-control-lg '}),
            'password': forms.PasswordInput(
                attrs={'class': 'form-control form-control-lg'}),
        }

main_app/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
import main_app.forms as _forms
import main_app.models as _models


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(redirect_to="login")
    else:
        return HttpResponseRedirect(redirect_to="principal")


class LoginFormView(LoginView):
    form_class = _forms.LoginForm
    template_name = "sign-in/login.html"
    success_url = reverse_lazy('principal')


class RegisterView(CreateView, SuccessMessageMixin):
    model = _models.User
    template_name = "sign-in/register.html"
    form_class = _forms.RegisterForm
    success_url = reverse_lazy('login')
    success_message = "Usuario registrado"


class PrincipalTemplateView(LoginRequiredMixin, TemplateView, PermissionRequiredMixin):
    template_name = "administrador_index.html"
    permission_required = 'main_app.view_user'


"""---------------------------------------------------------------
-----------------------------MEDICAMENTOS VIEW ------------------------
---------------------------------------------------------------"""


class MedicamentosView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/medicamentos.html'
    model = _models.Medicamento
    permission_required = "main_app.view_medicamento"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Medicamentos'
        return context


class MedicamentoDeleteView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    model = _models.Medicamento
    template_name = 'pages/admin_views/medicamentos.html'
    success_url = reverse_lazy('medicamentos')
    success_message = "El medicamento ha sido eliminado"
    permission_required = 'main_app.delete_medicamento'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar medicamento'
        return context


"""---------------------------------------------------------------
-----------------------------COMPRAS VIEW ------------------------
---------------------------------------------------------------"""


class ComprasView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/compras.html'
    permission_required = "main_app.view_compra"
    model = _models.Compra

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Compras'
        return context


"""---------------------------------------------------------------
-----------------------------TARJETA ESTIBA VIEW ------------------------
---------------------------------------------------------------"""


class TarjetasEstibaView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/tarjeta_estiba.html'
    permission_required = "main_app.view_tarjeta_estiba"
    model = _models.TarjetaEstiba

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tarjetas de Estiba'
        return context


"""---------------------------------------------------------------
-----------------------------TIPOS MEDICAMENTOS VIEW ------------------------
---------------------------------------------------------------"""


class TiposMedicamentosView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/tipo_medicamento.html'
    permission_required = "main_app.view_tipo_medicamento"
    model = _models.TipoMedicamento

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tipos de Medicamentos'
        return context


"""---------------------------------------------------------------
-----------------------------PEDIDOS VIEW ------------------------
---------------------------------------------------------------"""


class PedidosView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/pedidos.html'
    permission_required = "main_app.view_pedido"
    model = _models.Pedido

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Pedidos'
        return context


"""---------------------------------------------------------------
-----------------------------USUARIOS VIEW ------------------------
---------------------------------------------------------------"""


class UsuariosView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    template_name = 'pages/admin_views/usuarios.html'
    permission_required = "main_app.view_user"
    model = _models.User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Usuarios'
        return context

main_app/templates/pages/admin_views/compras.html
{% extends 'base_admin.html' %}
{% load static %}
{% block title %}Compras{% endblock title %}
{% block content_title %}Compras{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
<div
class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
>
<!-- Aki va la tabla -->
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="w-50">Tarjeta Bancaria</th>
      <th class="w-25">Fecha</th>
      <th class="w-50">Total pagado</th>
      {% if perms.main_app.change_compra or perms.main_app.delete_compra %}
        <th>Acciones</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for el in object_list %}
    <tr>
      <td>{{el.tarjeta_bancaria}}</td>
      <td>{{el.fecha}}</td>
      <td>{{el.total_pagado}}</td>
      {% if perms.main_app.change_compra or perms.main_app.delete_compra %}
      <td>
        <div
          class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
        >
          {% if perms.main_app.change_medicamento %}
          <a>
            <img
              src={% static 'images/icons/pen-fill.svg'%}
              alt="editar"
              style="width: 20px; height: 20px"
              class="btn btn-outline-light rounded-circle mx-1 p-0"
            />
          </a>
          {% endif %}
          {% if perms.main_app.delete_medicamento %} 
            <a href={% url 'delete_compra' %}>
              <img
                src={% static 'images/icons/trash-fill.svg'%}
                alt="eliminar"
                style="width: 20px; height: 20px"
                class="btn btn-outline-light rounded-circle p-0"
              />
            </a>
          {% endif %}
        </div>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
    
  </tbody>
</table>
</div>
{% endblock content_table %}

main_app/templates/pages/admin_views/medicamentos.html
{% extends 'base_admin.html' %}
{%load static%}
{% block title %}Medicamentos{% endblock title %}
{% block content_title %}Medicamentos{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
        <div
          class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
        >
          <!-- Aki va la tabla -->
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th class="w-50">Nombre</th>
                <th class="w-25">No. Serie</th>
                <th class="w-25">Fecha Caducidad</th>
                {% if perms.main_app.change_medicamento or perms.main_app.delete_medicamento %}
                  <th>Acciones</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
              {% for el in object_list %}
              <tr>
                <td>{{el.nombre}}</td>
                <td>{{el.no_lote}}</td>
                <td>{{el.fecha_cad}}</td>
                {% if perms.main_app.change_medicamento or perms.main_app.delete_medicamento %}
                <td>
                  <div
                    class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
                  >
                  {% if perms.main_app.change_medicamento %} 
                  <form method="PUT">
                    {% csrf_token %}
                    <button class="btn btn-ghost" type="submit">
                    <img
                      src={% static 'images/icons/pen-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle mx-1 p-0"
                    />
                  </button>
                </form>
                  {% endif %}
                    {% if perms.main_app.delete_medicamento %} 

                      <form method="POST">
                        {% csrf_token %}
                        <button class="btn btn-ghost" type="submit">
                          <img
                            src={% static 'images/icons/trash-fill.svg'%}
                            alt="eliminar"
                            style="width: 20px; height: 20px"
                            class="btn btn-outline-light rounded-circle p-0"
                          />
                        </button>
                      </form>

                    {% endif %}
                  </div>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
        </div>
{% endblock content_table %}
 

main_app/templates/pages/admin_views/pedidos.html
{% extends 'base_admin.html' %}
{%load static%}
{% block title %}Pedidos{% endblock title %}
{% block content_title %}Pedidos{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
<div
class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
>
<!-- Aki va la tabla -->
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="w-50">Fecha</th>
      <th class="w-50">Cant. Medicamentos</th>
      {% if perms.main_app.change_pedido or perms.main_app.delete_pedido %}
        <th>Acciones</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for el in object_list %}
    <tr>
      <td>{{el.fecha}}</td>
      <td>{{el.cantidad_medicamento}}</td>
      {% if perms.main_app.change_pedido or perms.main_app.delete_pedido %}
      <td>
        <div
          class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
        >
        {% if perms.main_app.change_pedido %} 
        <a>
          <img
            src={% static 'images/icons/pen-fill.svg'%}
            alt="editar"
            style="width: 20px; height: 20px"
            class="btn btn-outline-light rounded-circle mx-1 p-0"
          />
        </a>
        {% endif %}
          {% if perms.main_app.delete_pedido %} 
            <a href={% url 'delete_pedido' %}>
              <img
                src={% static 'images/icons/trash-fill.svg'%}
                alt="eliminar"
                style="width: 20px; height: 20px"
                class="btn btn-outline-light rounded-circle p-0"
              />
            </a>
          {% endif %}
        </div>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
    
  </tbody>
</table>
</div>
{% endblock content_table %}

main_app/templates/pages/admin_views/tarjeta_estiba.html
{% extends 'base_admin.html' %}
{%load static%}
{% block title %}Tarjeta de Estiba{% endblock title %}
{% block content_title %}Tarjeta de Estiba{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
        <div
          class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
        >
          <!-- Aki va la tabla -->
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th class="w-50">Nombre</th>
                <th class="w-50">No_Serie</th>
                <th class="w-25">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Alprazolan</td>
                <td>ASDBKAJSD</td>
                <td>
                  <div
                    class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
                  >
                    <img
                      src={% static 'images/icons/pen-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle mx-1 p-0"
                    />
                    <img
                      src={% static '/images/icons/trash-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle p-0"
                    />
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
{% endblock content_table %}

main_app/templates/pages/admin_views/tipo_medicamento.html
{% extends 'base_admin.html' %}
{%load static %}
{% block title %}Tipos de Medicamentos{% endblock title %}
{% block content_title %}Tipos de Medicamentos{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
        <div
          class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
        >
          <!-- Aki va la tabla -->
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th class="w-50">Nombre</th>
                <th class="w-50">No_Serie</th>
                <th class="w-25">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Alprazolan</td>
                <td>ASDBKAJSD</td>
                <td>
                  <div
                    class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
                  >
                    <img
                      src={%static '/images/icons/pen-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle mx-1 p-0"
                    />
                    <img
                      src={%static '/images/icons/trash-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle p-0"
                    />
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
{% endblock content_table %}

main_app/templates/pages/admin_views/usuarios.html
{% extends 'base_admin.html' %}
{%load static%}
{% block title %}Usuarios{% endblock title %}
{% block content_title %}Usuarios{% endblock content_title %}
{% block button_add %}<button class="btn btn-outline-primary">Agregar</button>{% endblock button_add %}
{% block content_table %}
        <div
          class="d-flex justify-content-center align-content-center w-100 h-0 p-3"
        >
          <!-- Aki va la tabla -->
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th class="w-50">Nombre</th>
                <th class="w-50">No_Serie</th>
                <th class="w-25">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>CuraDe todo</td>
                <td>Chupala</td>
                <td>
                  <div
                    class="d-flex flex-row p-1 m-0 justify-content-center align-content-center"
                  >
                    <img
                      src={% static '/images/icons/pen-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle mx-1 p-0"
                    />
                    <img
                      src={% static '/images/icons/trash-fill.svg'%}
                      alt="editar"
                      style="width: 20px; height: 20px"
                      class="btn btn-outline-light rounded-circle p-0"
                    />
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
{% endblock content_table %}